### ISSUE TITLE
Crash when I turn on putty

### ISSUE THREAD

**Issue by Barna13** [Grover-c13/MultiAdmin#157] opened 2018-05-05 13:06 UTC
Hello, sometime when i open putty the console crash and the server stay on.
646ec9044386ec4a7b3dd>:0
at MultiAdmin.MultiAdmin.Server.Write (System.String message, System.ConsoleColor color, System.Int32 height) [0x00031] in :0
at MultiAdmin.OutputThread.Read (MultiAdmin.MultiAdmin.Server server) [0x007da] in :0
at MultiAdmin.MultiAdmin.Server.<.ctor>b__55_1 () [0x00000] in :0
at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <65984520577646ec9044386ec4a7b3dd>:0
at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <65984520577646ec9044386ec4a7b3dd>:0
at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <65984520577646ec9044386ec4a7b3dd>:0
at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <65984520577646ec9044386ec4a7b3dd>:0
at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <65984520577646ec9044386ec4a7b3dd>:0

**Comment by SlenderPlays** [comment] 2018-05-15 10:34
Can you please describe step-by-step how to reproduce this issue?

**Comment by Barna13** [comment] 2018-05-15 11:46
It happens to me randomly when I connect to the server putty screen, the console crash but the server stays on

**Comment by Barna13** [comment] 2018-05-19 12:54
Yes again instantly  `at System.Console.set_CursorTop (System.Int32 value) [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0
  at MultiAdmin.MultiAdmin.Server.Write (System.String message, System.ConsoleColor color, System.Int32 height) [0x00031] in <fdd5c437452541bf804a7e01056a289c>:0
  at MultiAdmin.OutputThread.Read (MultiAdmin.MultiAdmin.Server server) [0x007da] in <fdd5c437452541bf804a7e01056a289c>:0
  at MultiAdmin.MultiAdmin.Server.<.ctor>b__55_1 () [0x00000] in <fdd5c437452541bf804a7e01056a289c>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <71d8ad678db34313b7f718a414dfcb25>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <71d8ad678db34313b7f718a414dfcb25>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <71d8ad678db34313b7f718a414dfcb25>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0
`

**Comment by SlenderPlays** [comment] 2018-05-19 13:45
So did you do anything in putty or did you just open it?

Ignore if not dev:

Here is a parsed version and an extracted version of the error:

> at System.Console.set_CursorTop (System.Int32 value) [0x00000] in 
>at MultiAdmin.MultiAdmin.Server.Write (System.String message, System.ConsoleColor color, System.Int32 height) in 
>at MultiAdmin.OutputThread.Read (MultiAdmin.MultiAdmin.Server server) in
>at MultiAdmin.MultiAdmin.Server.<.ctor>b__55_1 () in

**Comment by SlenderPlays** [comment] 2018-05-19 13:52
Update: I tried opening Putty, doing every time of connection, nothing yeilded  in crash. Can you please step by step specify what you did. Eg: 
Step 1: Open Putty 
Step 2: I put in localhost and port 777

etc.

I am unable to re-create the bug

**Comment by Dankrushen** [comment] 2018-05-22 16:55
Looks like a problem with whatever console or whatever you're using. Try updating mono and making sure you have all the dependencies.

**Comment by Barna13** [comment] 2018-05-25 11:41
I think I figured out how to reproduce the bug, as soon as I move the console putty the console crash

**Comment by Grover-c13** [comment] 2018-05-27 12:08
Duplicate of #138

**Closed by Grover-c13** 2018-05-27 12:08 UTC
