### ISSUE TITLE
MultiAdmin reports Invalid Handle

### ISSUE THREAD

**Issue by Kag3rou** [Grover-c13/MultiAdmin#140] opened 2018-03-09 19:08 UTC
![unknown](https://user-images.githubusercontent.com/37224689/37225028-e16991d0-239a-11e8-8492-45b376ec3b6a.png)

So, this happened after I tried to use my Discord Bot to run a Server.bat which CD'd to the MultiAdmin's location and runs it.

I believe this error also happens running it just by itself.

**Comment by Dankrushen** [comment] 2018-03-09 19:14
This looks like a possible issue with the TitleBar feature of MultiAdmin to me and I'm guessing it's not opening up in an actual Console window and that's why the problem is occurring. I may be wrong, but that's my thought on the issue.

**Comment by Kag3rou** [comment] 2018-03-09 19:17
@Dankrushen Is it fixable at all?

Kinda wanna integrate this with my bot so that we can start and stop the server from discord

**Comment by Dankrushen** [comment] 2018-03-09 19:18
I'll check it out in an hour or so.

**Comment by Dankrushen** [comment] 2018-03-09 20:15
I'm trying to see what's going on, but I can't seem to reproduce this issue, any chance you can tell me exactly about what you're trying to do?

What command are you running in the batch file to start the program?

**Comment by Kag3rou** [comment] 2018-03-10 00:46
So, my script looks like this

var child = require('child_process').execFile;
var executablePath = "SERVER BAT PATH";

global.serverProcess = child(executablePath, {maxBuffer: 1024 * 500}, function(err, data) {
    if(err){
       console.error(err);
       return;
    }
 
    console.Read(data.toString());
});

**Comment by Kag3rou** [comment] 2018-03-10 00:47
My BAT looks like this

cd C:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory
MultiAdmin.exe

**Comment by Grover-c13** [comment] 2018-03-10 03:08
Should be fixed with this commit https://github.com/Grover-c13/MultiAdmin/commit/69c90d5928381ce2e24baa355cf13b40b7f7d018

**Closed** 2018-03-10 07:54 UTC
Labels: bug
